FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y fortune cowsay netcat-openbsd dos2unix && rm -rf /var/lib/apt/lists/*

ENV PATH="$PATH:/usr/games"

WORKDIR /app

COPY wisecow.sh .

RUN dos2unix wisecow.sh && chmod +x wisecow.sh

EXPOSE 4499

CMD ["./wisecow.sh"]